services:
  _defaults:
    autowire: true
    autoconfigure: true

  Berecont\ContaoGalleryThumbBundle\:
    resource: ../src
    exclude: ../src/{ContaoManager,BerecontContaoGalleryThumbBundle.php}

